package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * CambioPreciosDet generated by hbm2java
 */
public class CambioPreciosDet  implements java.io.Serializable {


     private CambioPreciosDetId id;
     private CambioPreciosCab cambioPreciosCab;
     private BigDecimal precioCostoActual;
     private BigDecimal precioVentaActual;
     private BigDecimal precioVentaNuevo;
     private BigDecimal variacion;
     private String usuarioMod;
     private String accionMod;
     private Date fechaMod;

    public CambioPreciosDet() {
    }

	
    public CambioPreciosDet(CambioPreciosDetId id, CambioPreciosCab cambioPreciosCab) {
        this.id = id;
        this.cambioPreciosCab = cambioPreciosCab;
    }
    public CambioPreciosDet(CambioPreciosDetId id, CambioPreciosCab cambioPreciosCab, BigDecimal precioCostoActual, BigDecimal precioVentaActual, BigDecimal precioVentaNuevo, BigDecimal variacion, String usuarioMod, String accionMod, Date fechaMod) {
       this.id = id;
       this.cambioPreciosCab = cambioPreciosCab;
       this.precioCostoActual = precioCostoActual;
       this.precioVentaActual = precioVentaActual;
       this.precioVentaNuevo = precioVentaNuevo;
       this.variacion = variacion;
       this.usuarioMod = usuarioMod;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
    }
   
    public CambioPreciosDetId getId() {
        return this.id;
    }
    
    public void setId(CambioPreciosDetId id) {
        this.id = id;
    }
    public CambioPreciosCab getCambioPreciosCab() {
        return this.cambioPreciosCab;
    }
    
    public void setCambioPreciosCab(CambioPreciosCab cambioPreciosCab) {
        this.cambioPreciosCab = cambioPreciosCab;
    }
    public BigDecimal getPrecioCostoActual() {
        return this.precioCostoActual;
    }
    
    public void setPrecioCostoActual(BigDecimal precioCostoActual) {
        this.precioCostoActual = precioCostoActual;
    }
    public BigDecimal getPrecioVentaActual() {
        return this.precioVentaActual;
    }
    
    public void setPrecioVentaActual(BigDecimal precioVentaActual) {
        this.precioVentaActual = precioVentaActual;
    }
    public BigDecimal getPrecioVentaNuevo() {
        return this.precioVentaNuevo;
    }
    
    public void setPrecioVentaNuevo(BigDecimal precioVentaNuevo) {
        this.precioVentaNuevo = precioVentaNuevo;
    }
    public BigDecimal getVariacion() {
        return this.variacion;
    }
    
    public void setVariacion(BigDecimal variacion) {
        this.variacion = variacion;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


