package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0



/**
 * CobranzaDetId generated by hbm2java
 */
public class CobranzaDetId  implements java.io.Serializable {


     private int nroRecibo;
     private int linea;

    public CobranzaDetId() {
    }

    public CobranzaDetId(int nroRecibo, int linea) {
       this.nroRecibo = nroRecibo;
       this.linea = linea;
    }
   
    public int getNroRecibo() {
        return this.nroRecibo;
    }
    
    public void setNroRecibo(int nroRecibo) {
        this.nroRecibo = nroRecibo;
    }
    public int getLinea() {
        return this.linea;
    }
    
    public void setLinea(int linea) {
        this.linea = linea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CobranzaDetId) ) return false;
		 CobranzaDetId castOther = ( CobranzaDetId ) other; 
         
		 return (this.getNroRecibo()==castOther.getNroRecibo())
 && (this.getLinea()==castOther.getLinea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNroRecibo();
         result = 37 * result + this.getLinea();
         return result;
   }   


}


