package com.entidades;
// Generated 11/05/2014 07:53:35 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * FacturaVentaDetalle generated by hbm2java
 */
public class FacturaVentaDetalle  implements java.io.Serializable {


     private FacturaVentaDetalleId id;
     private MtArticulos mtArticulos;
     private BigDecimal cantidad;
     private BigDecimal precioUnitaio;
     private BigDecimal subtotal;
     private int porcIva;
     private BigDecimal importeIva;
     private BigDecimal porcDto;
     private BigDecimal impDescuento;
     private BigDecimal total;
     private String usuarioMod;
     private String accionMod;
     private Date fechaMod;

    public FacturaVentaDetalle() {
    }

	
    public FacturaVentaDetalle(FacturaVentaDetalleId id, MtArticulos mtArticulos, BigDecimal cantidad, BigDecimal precioUnitaio, BigDecimal subtotal, int porcIva, BigDecimal importeIva, BigDecimal porcDto, BigDecimal impDescuento, BigDecimal total) {
        this.id = id;
        this.mtArticulos = mtArticulos;
        this.cantidad = cantidad;
        this.precioUnitaio = precioUnitaio;
        this.subtotal = subtotal;
        this.porcIva = porcIva;
        this.importeIva = importeIva;
        this.porcDto = porcDto;
        this.impDescuento = impDescuento;
        this.total = total;
    }
    public FacturaVentaDetalle(FacturaVentaDetalleId id, MtArticulos mtArticulos, BigDecimal cantidad, BigDecimal precioUnitaio, BigDecimal subtotal, int porcIva, BigDecimal importeIva, BigDecimal porcDto, BigDecimal impDescuento, BigDecimal total, String usuarioMod, String accionMod, Date fechaMod) {
       this.id = id;
       this.mtArticulos = mtArticulos;
       this.cantidad = cantidad;
       this.precioUnitaio = precioUnitaio;
       this.subtotal = subtotal;
       this.porcIva = porcIva;
       this.importeIva = importeIva;
       this.porcDto = porcDto;
       this.impDescuento = impDescuento;
       this.total = total;
       this.usuarioMod = usuarioMod;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
    }
   
    public FacturaVentaDetalleId getId() {
        return this.id;
    }
    
    public void setId(FacturaVentaDetalleId id) {
        this.id = id;
    }
    public MtArticulos getMtArticulos() {
        return this.mtArticulos;
    }
    
    public void setMtArticulos(MtArticulos mtArticulos) {
        this.mtArticulos = mtArticulos;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnitaio() {
        return this.precioUnitaio;
    }
    
    public void setPrecioUnitaio(BigDecimal precioUnitaio) {
        this.precioUnitaio = precioUnitaio;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
    public int getPorcIva() {
        return this.porcIva;
    }
    
    public void setPorcIva(int porcIva) {
        this.porcIva = porcIva;
    }
    public BigDecimal getImporteIva() {
        return this.importeIva;
    }
    
    public void setImporteIva(BigDecimal importeIva) {
        this.importeIva = importeIva;
    }
    public BigDecimal getPorcDto() {
        return this.porcDto;
    }
    
    public void setPorcDto(BigDecimal porcDto) {
        this.porcDto = porcDto;
    }
    public BigDecimal getImpDescuento() {
        return this.impDescuento;
    }
    
    public void setImpDescuento(BigDecimal impDescuento) {
        this.impDescuento = impDescuento;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


