package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MtArticulos generated by hbm2java
 */
public class MtArticulos  implements java.io.Serializable {


     private String codArticulo;
     private MtUnidMedidas mtUnidMedidasByUniMedidaVenta;
     private MtTiposArticulos mtTiposArticulos;
     private MtUnidMedidas mtUnidMedidasByUniMedidaCom;
     private MtMarcas mtMarcas;
     private MtMonedas mtMonedasByCodMonedaVenta;
     private MtMonedas mtMonedasByCodMonedaCompra;
     private String nomArticulo;
     private String referencia;
     private BigDecimal precioCompra;
     private BigDecimal precioVenta;
     private char controlStock;
     private String usuarioMod;
     private String accionMod;
     private Date fechaMod;
     private Integer impuesto;
     private Character esMateriaPrima;
     private Boolean fraccionable;
     private Integer cantDiasVenc;
     private Set facturaVentaDetalles = new HashSet(0);
     private Set prProducs = new HashSet(0);
     private Set presupuestoDets = new HashSet(0);
     private Set stExistenciaSucs = new HashSet(0);
     private Set facturaCompraDetalles = new HashSet(0);
     private Set prProduccions = new HashSet(0);
     private Set prProduccions_1 = new HashSet(0);
     private Set ordCompraDets = new HashSet(0);
     private Set stExistenciaSucs_1 = new HashSet(0);

    public MtArticulos() {
    }

	
    public MtArticulos(String codArticulo, MtUnidMedidas mtUnidMedidasByUniMedidaCom, MtMonedas mtMonedasByCodMonedaVenta, MtMonedas mtMonedasByCodMonedaCompra, String nomArticulo, BigDecimal precioCompra, char controlStock) {
        this.codArticulo = codArticulo;
        this.mtUnidMedidasByUniMedidaCom = mtUnidMedidasByUniMedidaCom;
        this.mtMonedasByCodMonedaVenta = mtMonedasByCodMonedaVenta;
        this.mtMonedasByCodMonedaCompra = mtMonedasByCodMonedaCompra;
        this.nomArticulo = nomArticulo;
        this.precioCompra = precioCompra;
        this.controlStock = controlStock;
    }
    public MtArticulos(String codArticulo, MtUnidMedidas mtUnidMedidasByUniMedidaVenta, MtTiposArticulos mtTiposArticulos, MtUnidMedidas mtUnidMedidasByUniMedidaCom, MtMarcas mtMarcas, MtMonedas mtMonedasByCodMonedaVenta, MtMonedas mtMonedasByCodMonedaCompra, String nomArticulo, String referencia, BigDecimal precioCompra, BigDecimal precioVenta, char controlStock, String usuarioMod, String accionMod, Date fechaMod, Integer impuesto, Character esMateriaPrima, Boolean fraccionable, Integer cantDiasVenc, Set facturaVentaDetalles, Set prProducs, Set presupuestoDets, Set stExistenciaSucs, Set facturaCompraDetalles, Set prProduccions, Set prProduccions_1, Set ordCompraDets, Set stExistenciaSucs_1) {
       this.codArticulo = codArticulo;
       this.mtUnidMedidasByUniMedidaVenta = mtUnidMedidasByUniMedidaVenta;
       this.mtTiposArticulos = mtTiposArticulos;
       this.mtUnidMedidasByUniMedidaCom = mtUnidMedidasByUniMedidaCom;
       this.mtMarcas = mtMarcas;
       this.mtMonedasByCodMonedaVenta = mtMonedasByCodMonedaVenta;
       this.mtMonedasByCodMonedaCompra = mtMonedasByCodMonedaCompra;
       this.nomArticulo = nomArticulo;
       this.referencia = referencia;
       this.precioCompra = precioCompra;
       this.precioVenta = precioVenta;
       this.controlStock = controlStock;
       this.usuarioMod = usuarioMod;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
       this.impuesto = impuesto;
       this.esMateriaPrima = esMateriaPrima;
       this.fraccionable = fraccionable;
       this.cantDiasVenc = cantDiasVenc;
       this.facturaVentaDetalles = facturaVentaDetalles;
       this.prProducs = prProducs;
       this.presupuestoDets = presupuestoDets;
       this.stExistenciaSucs = stExistenciaSucs;
       this.facturaCompraDetalles = facturaCompraDetalles;
       this.prProduccions = prProduccions;
       this.prProduccions_1 = prProduccions_1;
       this.ordCompraDets = ordCompraDets;
       this.stExistenciaSucs_1 = stExistenciaSucs_1;
    }
   
    public String getCodArticulo() {
        return this.codArticulo;
    }
    
    public void setCodArticulo(String codArticulo) {
        this.codArticulo = codArticulo;
    }
    public MtUnidMedidas getMtUnidMedidasByUniMedidaVenta() {
        return this.mtUnidMedidasByUniMedidaVenta;
    }
    
    public void setMtUnidMedidasByUniMedidaVenta(MtUnidMedidas mtUnidMedidasByUniMedidaVenta) {
        this.mtUnidMedidasByUniMedidaVenta = mtUnidMedidasByUniMedidaVenta;
    }
    public MtTiposArticulos getMtTiposArticulos() {
        return this.mtTiposArticulos;
    }
    
    public void setMtTiposArticulos(MtTiposArticulos mtTiposArticulos) {
        this.mtTiposArticulos = mtTiposArticulos;
    }
    public MtUnidMedidas getMtUnidMedidasByUniMedidaCom() {
        return this.mtUnidMedidasByUniMedidaCom;
    }
    
    public void setMtUnidMedidasByUniMedidaCom(MtUnidMedidas mtUnidMedidasByUniMedidaCom) {
        this.mtUnidMedidasByUniMedidaCom = mtUnidMedidasByUniMedidaCom;
    }
    public MtMarcas getMtMarcas() {
        return this.mtMarcas;
    }
    
    public void setMtMarcas(MtMarcas mtMarcas) {
        this.mtMarcas = mtMarcas;
    }
    public MtMonedas getMtMonedasByCodMonedaVenta() {
        return this.mtMonedasByCodMonedaVenta;
    }
    
    public void setMtMonedasByCodMonedaVenta(MtMonedas mtMonedasByCodMonedaVenta) {
        this.mtMonedasByCodMonedaVenta = mtMonedasByCodMonedaVenta;
    }
    public MtMonedas getMtMonedasByCodMonedaCompra() {
        return this.mtMonedasByCodMonedaCompra;
    }
    
    public void setMtMonedasByCodMonedaCompra(MtMonedas mtMonedasByCodMonedaCompra) {
        this.mtMonedasByCodMonedaCompra = mtMonedasByCodMonedaCompra;
    }
    public String getNomArticulo() {
        return this.nomArticulo;
    }
    
    public void setNomArticulo(String nomArticulo) {
        this.nomArticulo = nomArticulo;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public char getControlStock() {
        return this.controlStock;
    }
    
    public void setControlStock(char controlStock) {
        this.controlStock = controlStock;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }
    public Integer getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(Integer impuesto) {
        this.impuesto = impuesto;
    }
    public Character getEsMateriaPrima() {
        return this.esMateriaPrima;
    }
    
    public void setEsMateriaPrima(Character esMateriaPrima) {
        this.esMateriaPrima = esMateriaPrima;
    }
    public Boolean getFraccionable() {
        return this.fraccionable;
    }
    
    public void setFraccionable(Boolean fraccionable) {
        this.fraccionable = fraccionable;
    }
    public Integer getCantDiasVenc() {
        return this.cantDiasVenc;
    }
    
    public void setCantDiasVenc(Integer cantDiasVenc) {
        this.cantDiasVenc = cantDiasVenc;
    }
    public Set getFacturaVentaDetalles() {
        return this.facturaVentaDetalles;
    }
    
    public void setFacturaVentaDetalles(Set facturaVentaDetalles) {
        this.facturaVentaDetalles = facturaVentaDetalles;
    }
    public Set getPrProducs() {
        return this.prProducs;
    }
    
    public void setPrProducs(Set prProducs) {
        this.prProducs = prProducs;
    }
    public Set getPresupuestoDets() {
        return this.presupuestoDets;
    }
    
    public void setPresupuestoDets(Set presupuestoDets) {
        this.presupuestoDets = presupuestoDets;
    }
    public Set getStExistenciaSucs() {
        return this.stExistenciaSucs;
    }
    
    public void setStExistenciaSucs(Set stExistenciaSucs) {
        this.stExistenciaSucs = stExistenciaSucs;
    }
    public Set getFacturaCompraDetalles() {
        return this.facturaCompraDetalles;
    }
    
    public void setFacturaCompraDetalles(Set facturaCompraDetalles) {
        this.facturaCompraDetalles = facturaCompraDetalles;
    }
    public Set getPrProduccions() {
        return this.prProduccions;
    }
    
    public void setPrProduccions(Set prProduccions) {
        this.prProduccions = prProduccions;
    }
    public Set getPrProduccions_1() {
        return this.prProduccions_1;
    }
    
    public void setPrProduccions_1(Set prProduccions_1) {
        this.prProduccions_1 = prProduccions_1;
    }
    public Set getOrdCompraDets() {
        return this.ordCompraDets;
    }
    
    public void setOrdCompraDets(Set ordCompraDets) {
        this.ordCompraDets = ordCompraDets;
    }
    public Set getStExistenciaSucs_1() {
        return this.stExistenciaSucs_1;
    }
    
    public void setStExistenciaSucs_1(Set stExistenciaSucs_1) {
        this.stExistenciaSucs_1 = stExistenciaSucs_1;
    }




}


