package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MtPaises generated by hbm2java
 */
public class MtPaises  implements java.io.Serializable {


     private int codPais;
     private String nomPais;
     private String usuarioMod;
     private String accionMod;
     private Date fechaMod;
     private Set mtDepartamentoses = new HashSet(0);
     private Set mtEmpleadoses = new HashSet(0);
     private Set mtDepartamentoses_1 = new HashSet(0);

    public MtPaises() {
    }

	
    public MtPaises(int codPais, String nomPais) {
        this.codPais = codPais;
        this.nomPais = nomPais;
    }
    public MtPaises(int codPais, String nomPais, String usuarioMod, String accionMod, Date fechaMod, Set mtDepartamentoses, Set mtEmpleadoses, Set mtDepartamentoses_1) {
       this.codPais = codPais;
       this.nomPais = nomPais;
       this.usuarioMod = usuarioMod;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
       this.mtDepartamentoses = mtDepartamentoses;
       this.mtEmpleadoses = mtEmpleadoses;
       this.mtDepartamentoses_1 = mtDepartamentoses_1;
    }
   
    public int getCodPais() {
        return this.codPais;
    }
    
    public void setCodPais(int codPais) {
        this.codPais = codPais;
    }
    public String getNomPais() {
        return this.nomPais;
    }
    
    public void setNomPais(String nomPais) {
        this.nomPais = nomPais;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }
    public Set getMtDepartamentoses() {
        return this.mtDepartamentoses;
    }
    
    public void setMtDepartamentoses(Set mtDepartamentoses) {
        this.mtDepartamentoses = mtDepartamentoses;
    }
    public Set getMtEmpleadoses() {
        return this.mtEmpleadoses;
    }
    
    public void setMtEmpleadoses(Set mtEmpleadoses) {
        this.mtEmpleadoses = mtEmpleadoses;
    }
    public Set getMtDepartamentoses_1() {
        return this.mtDepartamentoses_1;
    }
    
    public void setMtDepartamentoses_1(Set mtDepartamentoses_1) {
        this.mtDepartamentoses_1 = mtDepartamentoses_1;
    }




}


