package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * MtProcTarjetas generated by hbm2java
 */
public class MtProcTarjetas  implements java.io.Serializable {


     private int idProc;
     private String nombreProc;
     private String accionMod;
     private Date fechaMod;
     private String usuarioMod;
     private BigDecimal comision;

    public MtProcTarjetas() {
    }

	
    public MtProcTarjetas(int idProc) {
        this.idProc = idProc;
    }
    public MtProcTarjetas(int idProc, String nombreProc, String accionMod, Date fechaMod, String usuarioMod, BigDecimal comision) {
       this.idProc = idProc;
       this.nombreProc = nombreProc;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
       this.usuarioMod = usuarioMod;
       this.comision = comision;
    }
   
    public int getIdProc() {
        return this.idProc;
    }
    
    public void setIdProc(int idProc) {
        this.idProc = idProc;
    }
    public String getNombreProc() {
        return this.nombreProc;
    }
    
    public void setNombreProc(String nombreProc) {
        this.nombreProc = nombreProc;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public BigDecimal getComision() {
        return this.comision;
    }
    
    public void setComision(BigDecimal comision) {
        this.comision = comision;
    }




}


