package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MtUnidMedidas generated by hbm2java
 */
public class MtUnidMedidas  implements java.io.Serializable {


     private String codUnidad;
     private String descUnidad;
     private String simbolo;
     private short fracciones;
     private String usuarioMod;
     private String accionMod;
     private Date fechaMod;
     private Set mtConversionUnidadeses = new HashSet(0);
     private Set mtArticulosesForUniMedidaVenta = new HashSet(0);
     private Set mtArticulosesForUniMedidaCom = new HashSet(0);
     private Set mtArticulosesForUniMedidaVenta_1 = new HashSet(0);

    public MtUnidMedidas() {
    }

	
    public MtUnidMedidas(String codUnidad, String descUnidad, String simbolo, short fracciones) {
        this.codUnidad = codUnidad;
        this.descUnidad = descUnidad;
        this.simbolo = simbolo;
        this.fracciones = fracciones;
    }
    public MtUnidMedidas(String codUnidad, String descUnidad, String simbolo, short fracciones, String usuarioMod, String accionMod, Date fechaMod, Set mtConversionUnidadeses, Set mtArticulosesForUniMedidaVenta, Set mtArticulosesForUniMedidaCom, Set mtArticulosesForUniMedidaVenta_1) {
       this.codUnidad = codUnidad;
       this.descUnidad = descUnidad;
       this.simbolo = simbolo;
       this.fracciones = fracciones;
       this.usuarioMod = usuarioMod;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
       this.mtConversionUnidadeses = mtConversionUnidadeses;
       this.mtArticulosesForUniMedidaVenta = mtArticulosesForUniMedidaVenta;
       this.mtArticulosesForUniMedidaCom = mtArticulosesForUniMedidaCom;
       this.mtArticulosesForUniMedidaVenta_1 = mtArticulosesForUniMedidaVenta_1;
    }
   
    public String getCodUnidad() {
        return this.codUnidad;
    }
    
    public void setCodUnidad(String codUnidad) {
        this.codUnidad = codUnidad;
    }
    public String getDescUnidad() {
        return this.descUnidad;
    }
    
    public void setDescUnidad(String descUnidad) {
        this.descUnidad = descUnidad;
    }
    public String getSimbolo() {
        return this.simbolo;
    }
    
    public void setSimbolo(String simbolo) {
        this.simbolo = simbolo;
    }
    public short getFracciones() {
        return this.fracciones;
    }
    
    public void setFracciones(short fracciones) {
        this.fracciones = fracciones;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }
    public Set getMtConversionUnidadeses() {
        return this.mtConversionUnidadeses;
    }
    
    public void setMtConversionUnidadeses(Set mtConversionUnidadeses) {
        this.mtConversionUnidadeses = mtConversionUnidadeses;
    }
    public Set getMtArticulosesForUniMedidaVenta() {
        return this.mtArticulosesForUniMedidaVenta;
    }
    
    public void setMtArticulosesForUniMedidaVenta(Set mtArticulosesForUniMedidaVenta) {
        this.mtArticulosesForUniMedidaVenta = mtArticulosesForUniMedidaVenta;
    }
    public Set getMtArticulosesForUniMedidaCom() {
        return this.mtArticulosesForUniMedidaCom;
    }
    
    public void setMtArticulosesForUniMedidaCom(Set mtArticulosesForUniMedidaCom) {
        this.mtArticulosesForUniMedidaCom = mtArticulosesForUniMedidaCom;
    }
    public Set getMtArticulosesForUniMedidaVenta_1() {
        return this.mtArticulosesForUniMedidaVenta_1;
    }
    
    public void setMtArticulosesForUniMedidaVenta_1(Set mtArticulosesForUniMedidaVenta_1) {
        this.mtArticulosesForUniMedidaVenta_1 = mtArticulosesForUniMedidaVenta_1;
    }




}


