package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * MtVendedores generated by hbm2java
 */
public class MtVendedores  implements java.io.Serializable {


     private int codVendedor;
     private MtSucursales mtSucursales;
     private String nomVendedor;
     private char esActivo;
     private String usuarioMod;
     private String accionMod;
     private Date fechaMod;

    public MtVendedores() {
    }

	
    public MtVendedores(int codVendedor, MtSucursales mtSucursales, String nomVendedor, char esActivo) {
        this.codVendedor = codVendedor;
        this.mtSucursales = mtSucursales;
        this.nomVendedor = nomVendedor;
        this.esActivo = esActivo;
    }
    public MtVendedores(int codVendedor, MtSucursales mtSucursales, String nomVendedor, char esActivo, String usuarioMod, String accionMod, Date fechaMod) {
       this.codVendedor = codVendedor;
       this.mtSucursales = mtSucursales;
       this.nomVendedor = nomVendedor;
       this.esActivo = esActivo;
       this.usuarioMod = usuarioMod;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
    }
   
    public int getCodVendedor() {
        return this.codVendedor;
    }
    
    public void setCodVendedor(int codVendedor) {
        this.codVendedor = codVendedor;
    }
    public MtSucursales getMtSucursales() {
        return this.mtSucursales;
    }
    
    public void setMtSucursales(MtSucursales mtSucursales) {
        this.mtSucursales = mtSucursales;
    }
    public String getNomVendedor() {
        return this.nomVendedor;
    }
    
    public void setNomVendedor(String nomVendedor) {
        this.nomVendedor = nomVendedor;
    }
    public char getEsActivo() {
        return this.esActivo;
    }
    
    public void setEsActivo(char esActivo) {
        this.esActivo = esActivo;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


