package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * OrdCompraDet generated by hbm2java
 */
public class OrdCompraDet  implements java.io.Serializable {


     private OrdCompraDetId id;
     private OrdenCompra ordenCompra;
     private MtArticulos mtArticulos;
     private int cantidad;
     private BigDecimal precioUnitario;
     private BigDecimal subtotal;
     private int porcIva;
     private BigDecimal importeIva;
     private int porcDto;
     private BigDecimal impDescuento;
     private BigDecimal total;
     private String usuarioMod;
     private String accionMod;
     private Date fechaMod;

    public OrdCompraDet() {
    }

	
    public OrdCompraDet(OrdCompraDetId id, OrdenCompra ordenCompra, MtArticulos mtArticulos, int cantidad, BigDecimal precioUnitario, BigDecimal subtotal, int porcIva, BigDecimal importeIva, int porcDto, BigDecimal impDescuento) {
        this.id = id;
        this.ordenCompra = ordenCompra;
        this.mtArticulos = mtArticulos;
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
        this.subtotal = subtotal;
        this.porcIva = porcIva;
        this.importeIva = importeIva;
        this.porcDto = porcDto;
        this.impDescuento = impDescuento;
    }
    public OrdCompraDet(OrdCompraDetId id, OrdenCompra ordenCompra, MtArticulos mtArticulos, int cantidad, BigDecimal precioUnitario, BigDecimal subtotal, int porcIva, BigDecimal importeIva, int porcDto, BigDecimal impDescuento, BigDecimal total, String usuarioMod, String accionMod, Date fechaMod) {
       this.id = id;
       this.ordenCompra = ordenCompra;
       this.mtArticulos = mtArticulos;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.subtotal = subtotal;
       this.porcIva = porcIva;
       this.importeIva = importeIva;
       this.porcDto = porcDto;
       this.impDescuento = impDescuento;
       this.total = total;
       this.usuarioMod = usuarioMod;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
    }
   
    public OrdCompraDetId getId() {
        return this.id;
    }
    
    public void setId(OrdCompraDetId id) {
        this.id = id;
    }
    public OrdenCompra getOrdenCompra() {
        return this.ordenCompra;
    }
    
    public void setOrdenCompra(OrdenCompra ordenCompra) {
        this.ordenCompra = ordenCompra;
    }
    public MtArticulos getMtArticulos() {
        return this.mtArticulos;
    }
    
    public void setMtArticulos(MtArticulos mtArticulos) {
        this.mtArticulos = mtArticulos;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
    public int getPorcIva() {
        return this.porcIva;
    }
    
    public void setPorcIva(int porcIva) {
        this.porcIva = porcIva;
    }
    public BigDecimal getImporteIva() {
        return this.importeIva;
    }
    
    public void setImporteIva(BigDecimal importeIva) {
        this.importeIva = importeIva;
    }
    public int getPorcDto() {
        return this.porcDto;
    }
    
    public void setPorcDto(int porcDto) {
        this.porcDto = porcDto;
    }
    public BigDecimal getImpDescuento() {
        return this.impDescuento;
    }
    
    public void setImpDescuento(BigDecimal impDescuento) {
        this.impDescuento = impDescuento;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


