package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * PresupuestoDet generated by hbm2java
 */
public class PresupuestoDet  implements java.io.Serializable {


     private PresupuestoDetId id;
     private PresupuestoCab presupuestoCab;
     private MtArticulos mtArticulos;
     private int nroPresupuesto;
     private int linea;
     private BigDecimal precioUnitarioMn;
     private Integer codMoneda;
     private BigDecimal tipoCambio;
     private BigDecimal precioUnitario;
     private int cantidad;
     private BigDecimal subtotal;
     private BigDecimal porcDto;
     private BigDecimal impDescuento;
     private BigDecimal total;
     private int porcIva;
     private BigDecimal importeIva;
     private String usuarioMod;
     private String accionMod;
     private Date fechaMod;

    public PresupuestoDet() {
    }

	
    public PresupuestoDet(PresupuestoDetId id, PresupuestoCab presupuestoCab, MtArticulos mtArticulos, int nroPresupuesto, int linea, BigDecimal precioUnitarioMn, BigDecimal tipoCambio, BigDecimal precioUnitario, int cantidad, BigDecimal subtotal, BigDecimal porcDto, BigDecimal impDescuento, BigDecimal total, int porcIva, BigDecimal importeIva) {
        this.id = id;
        this.presupuestoCab = presupuestoCab;
        this.mtArticulos = mtArticulos;
        this.nroPresupuesto = nroPresupuesto;
        this.linea = linea;
        this.precioUnitarioMn = precioUnitarioMn;
        this.tipoCambio = tipoCambio;
        this.precioUnitario = precioUnitario;
        this.cantidad = cantidad;
        this.subtotal = subtotal;
        this.porcDto = porcDto;
        this.impDescuento = impDescuento;
        this.total = total;
        this.porcIva = porcIva;
        this.importeIva = importeIva;
    }
    public PresupuestoDet(PresupuestoDetId id, PresupuestoCab presupuestoCab, MtArticulos mtArticulos, int nroPresupuesto, int linea, BigDecimal precioUnitarioMn, Integer codMoneda, BigDecimal tipoCambio, BigDecimal precioUnitario, int cantidad, BigDecimal subtotal, BigDecimal porcDto, BigDecimal impDescuento, BigDecimal total, int porcIva, BigDecimal importeIva, String usuarioMod, String accionMod, Date fechaMod) {
       this.id = id;
       this.presupuestoCab = presupuestoCab;
       this.mtArticulos = mtArticulos;
       this.nroPresupuesto = nroPresupuesto;
       this.linea = linea;
       this.precioUnitarioMn = precioUnitarioMn;
       this.codMoneda = codMoneda;
       this.tipoCambio = tipoCambio;
       this.precioUnitario = precioUnitario;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
       this.porcDto = porcDto;
       this.impDescuento = impDescuento;
       this.total = total;
       this.porcIva = porcIva;
       this.importeIva = importeIva;
       this.usuarioMod = usuarioMod;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
    }
   
    public PresupuestoDetId getId() {
        return this.id;
    }
    
    public void setId(PresupuestoDetId id) {
        this.id = id;
    }
    public PresupuestoCab getPresupuestoCab() {
        return this.presupuestoCab;
    }
    
    public void setPresupuestoCab(PresupuestoCab presupuestoCab) {
        this.presupuestoCab = presupuestoCab;
    }
    public MtArticulos getMtArticulos() {
        return this.mtArticulos;
    }
    
    public void setMtArticulos(MtArticulos mtArticulos) {
        this.mtArticulos = mtArticulos;
    }
    public int getNroPresupuesto() {
        return this.nroPresupuesto;
    }
    
    public void setNroPresupuesto(int nroPresupuesto) {
        this.nroPresupuesto = nroPresupuesto;
    }
    public int getLinea() {
        return this.linea;
    }
    
    public void setLinea(int linea) {
        this.linea = linea;
    }
    public BigDecimal getPrecioUnitarioMn() {
        return this.precioUnitarioMn;
    }
    
    public void setPrecioUnitarioMn(BigDecimal precioUnitarioMn) {
        this.precioUnitarioMn = precioUnitarioMn;
    }
    public Integer getCodMoneda() {
        return this.codMoneda;
    }
    
    public void setCodMoneda(Integer codMoneda) {
        this.codMoneda = codMoneda;
    }
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
    public BigDecimal getPorcDto() {
        return this.porcDto;
    }
    
    public void setPorcDto(BigDecimal porcDto) {
        this.porcDto = porcDto;
    }
    public BigDecimal getImpDescuento() {
        return this.impDescuento;
    }
    
    public void setImpDescuento(BigDecimal impDescuento) {
        this.impDescuento = impDescuento;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public int getPorcIva() {
        return this.porcIva;
    }
    
    public void setPorcIva(int porcIva) {
        this.porcIva = porcIva;
    }
    public BigDecimal getImporteIva() {
        return this.importeIva;
    }
    
    public void setImporteIva(BigDecimal importeIva) {
        this.importeIva = importeIva;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


