package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * SaPendientes generated by hbm2java
 */
public class SaPendientes  implements java.io.Serializable {


     private int nroTrans;
     private String codDocum;
     private String codTit;
     private String codSucFac;
     private String codTributFac;
     private Integer nroDocum;
     private Date fecDoc;
     private Date vencimiento;
     private int codMoneda;
     private BigDecimal importeOrigen;
     private BigDecimal saldo;
     private String usuarioMod;
     private String accionMod;
     private Date fechaMod;

    public SaPendientes() {
    }

	
    public SaPendientes(int nroTrans, String codDocum, String codTit, int codMoneda) {
        this.nroTrans = nroTrans;
        this.codDocum = codDocum;
        this.codTit = codTit;
        this.codMoneda = codMoneda;
    }
    public SaPendientes(int nroTrans, String codDocum, String codTit, String codSucFac, String codTributFac, Integer nroDocum, Date fecDoc, Date vencimiento, int codMoneda, BigDecimal importeOrigen, BigDecimal saldo, String usuarioMod, String accionMod, Date fechaMod) {
       this.nroTrans = nroTrans;
       this.codDocum = codDocum;
       this.codTit = codTit;
       this.codSucFac = codSucFac;
       this.codTributFac = codTributFac;
       this.nroDocum = nroDocum;
       this.fecDoc = fecDoc;
       this.vencimiento = vencimiento;
       this.codMoneda = codMoneda;
       this.importeOrigen = importeOrigen;
       this.saldo = saldo;
       this.usuarioMod = usuarioMod;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
    }
   
    public int getNroTrans() {
        return this.nroTrans;
    }
    
    public void setNroTrans(int nroTrans) {
        this.nroTrans = nroTrans;
    }
    public String getCodDocum() {
        return this.codDocum;
    }
    
    public void setCodDocum(String codDocum) {
        this.codDocum = codDocum;
    }
    public String getCodTit() {
        return this.codTit;
    }
    
    public void setCodTit(String codTit) {
        this.codTit = codTit;
    }
    public String getCodSucFac() {
        return this.codSucFac;
    }
    
    public void setCodSucFac(String codSucFac) {
        this.codSucFac = codSucFac;
    }
    public String getCodTributFac() {
        return this.codTributFac;
    }
    
    public void setCodTributFac(String codTributFac) {
        this.codTributFac = codTributFac;
    }
    public Integer getNroDocum() {
        return this.nroDocum;
    }
    
    public void setNroDocum(Integer nroDocum) {
        this.nroDocum = nroDocum;
    }
    public Date getFecDoc() {
        return this.fecDoc;
    }
    
    public void setFecDoc(Date fecDoc) {
        this.fecDoc = fecDoc;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public int getCodMoneda() {
        return this.codMoneda;
    }
    
    public void setCodMoneda(int codMoneda) {
        this.codMoneda = codMoneda;
    }
    public BigDecimal getImporteOrigen() {
        return this.importeOrigen;
    }
    
    public void setImporteOrigen(BigDecimal importeOrigen) {
        this.importeOrigen = importeOrigen;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


