package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TsBancosCtas generated by hbm2java
 */
public class TsBancosCtas  implements java.io.Serializable {

     private TsBancosCtasId id;
     private MtMonedas mtMonedas;
     private MtBancos mtBancos;
     private String usuarioMod;
     private String accionMod;
     private Date fechaMod;
     private BigDecimal saldoCuenta;
     private Set mtChequeses = new HashSet(0);
     private Set movValoreses = new HashSet(0);

    public TsBancosCtas() {
    }

	
    public TsBancosCtas(TsBancosCtasId id, MtMonedas mtMonedas, MtBancos mtBancos) {
        this.id = id;
        this.mtMonedas = mtMonedas;
        this.mtBancos = mtBancos;
    }
    
    public TsBancosCtas(TsBancosCtasId id, MtMonedas mtMonedas, MtBancos mtBancos, String usuarioMod, String accionMod, Date fechaMod, BigDecimal saldoCuenta, Set mtChequeses, Set movValoreses) {
       this.id = id;
       this.mtMonedas = mtMonedas;
       this.mtBancos = mtBancos;
       this.usuarioMod = usuarioMod;
       this.accionMod = accionMod;
       this.fechaMod = fechaMod;
       this.saldoCuenta = saldoCuenta;
       this.mtChequeses = mtChequeses;
       this.movValoreses = movValoreses;
    }
   
    public TsBancosCtasId getId() {
        return this.id;
    }
    
    public void setId(TsBancosCtasId id) {
        this.id = id;
    }
    public MtMonedas getMtMonedas() {
        return this.mtMonedas;
    }
    
    public void setMtMonedas(MtMonedas mtMonedas) {
        this.mtMonedas = mtMonedas;
    }
    public MtBancos getMtBancos() {
        return this.mtBancos;
    }
    
    public void setMtBancos(MtBancos mtBancos) {
        this.mtBancos = mtBancos;
    }
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }
    public String getAccionMod() {
        return this.accionMod;
    }
    
    public void setAccionMod(String accionMod) {
        this.accionMod = accionMod;
    }
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }
    public BigDecimal getSaldoCuenta() {
        return this.saldoCuenta;
    }
    
    public void setSaldoCuenta(BigDecimal saldoCuenta) {
        this.saldoCuenta = saldoCuenta;
    }
    public Set getMtChequeses() {
        return this.mtChequeses;
    }
    
    public void setMtChequeses(Set mtChequeses) {
        this.mtChequeses = mtChequeses;
    }
    public Set getMovValoreses() {
        return this.movValoreses;
    }
    
    public void setMovValoreses(Set movValoreses) {
        this.movValoreses = movValoreses;
    }




}


