package com.entidades;
// Generated 22/06/2014 01:16:55 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * ValoresDet generated by hbm2java
 */
public class ValoresDet  implements java.io.Serializable {


     private ValoresDetId id;
     private Integer codFormaPago;
     private Integer codEmisor;
     private Integer codMoneda;
     private Integer tipoCambio;
     private String refOperacion;
     private BigDecimal importe;
     private Integer cuotas;
     private Integer refDocum;

    public ValoresDet() {
    }

	
    public ValoresDet(ValoresDetId id) {
        this.id = id;
    }
    public ValoresDet(ValoresDetId id, Integer codFormaPago, Integer codEmisor, Integer codMoneda, Integer tipoCambio, String refOperacion, BigDecimal importe, Integer cuotas, Integer refDocum) {
       this.id = id;
       this.codFormaPago = codFormaPago;
       this.codEmisor = codEmisor;
       this.codMoneda = codMoneda;
       this.tipoCambio = tipoCambio;
       this.refOperacion = refOperacion;
       this.importe = importe;
       this.cuotas = cuotas;
       this.refDocum = refDocum;
    }
   
    public ValoresDetId getId() {
        return this.id;
    }
    
    public void setId(ValoresDetId id) {
        this.id = id;
    }
    public Integer getCodFormaPago() {
        return this.codFormaPago;
    }
    
    public void setCodFormaPago(Integer codFormaPago) {
        this.codFormaPago = codFormaPago;
    }
    public Integer getCodEmisor() {
        return this.codEmisor;
    }
    
    public void setCodEmisor(Integer codEmisor) {
        this.codEmisor = codEmisor;
    }
    public Integer getCodMoneda() {
        return this.codMoneda;
    }
    
    public void setCodMoneda(Integer codMoneda) {
        this.codMoneda = codMoneda;
    }
    public Integer getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(Integer tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    public String getRefOperacion() {
        return this.refOperacion;
    }
    
    public void setRefOperacion(String refOperacion) {
        this.refOperacion = refOperacion;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public Integer getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Integer cuotas) {
        this.cuotas = cuotas;
    }
    public Integer getRefDocum() {
        return this.refDocum;
    }
    
    public void setRefDocum(Integer refDocum) {
        this.refDocum = refDocum;
    }




}


