/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.stock;

import com.entidades.StExistenciaSuc;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import util.FormatearNumero;
import util.HibernateUtil;

/**
 *
 * @author vanessa
 */
public class StockMinimo extends javax.swing.JDialog {

    StExistenciaSuc entidad;
    private Session st;
    private String usuario;
       

    /**
     * Creates new form NewJDialog
     */
    public StockMinimo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public StockMinimo(StExistenciaSuc s) {
        initComponents();
        entidad = s;
        initValues();
    }

    public StockMinimo(StExistenciaSuc s, String usuario) {
        initComponents();
        entidad = s;
        this.usuario = usuario;
        initValues();

    }
    
    private void initValues() {
        textNombreArticulo.setText(entidad.getMtArticulos().getNomArticulo());
        textFieldNombreSucursal.setText(entidad.getMtSucursales().getNomSucursal());
        textFieldCantidad.setText(entidad.getCantidad().toString());
        textFieldStockMinimo.setText(entidad.getStockMinimo().toString());
        textFieldTipoArticulo.setText(entidad.getMtArticulos().getMtTiposArticulos().getNomTipoArticulo());
        habilitarCampos();
    }

    private void habilitarCampos() {
        this.botonGuardar.setEnabled(true);
        this.botonCancelar.setEnabled(true);
    }

    private void deshabilitarCampos() {
        this.botonGuardar.setEnabled(false);
        this.botonCancelar.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtFechaHora1 = new javax.swing.JTextField();
        txtCodUsuario1 = new javax.swing.JTextField();
        txtNomUsuario1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNombreArticulo = new javax.swing.JTextField();
        textFieldCantidad = new javax.swing.JTextField();
        textFieldNombreSucursal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldStockMinimo = new javax.swing.JTextField();
        textFieldTipoArticulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Save.png"))); // NOI18N
        botonGuardar.setToolTipText("Guardar");
        botonGuardar.setEnabled(false);
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/cancel32.png"))); // NOI18N
        botonCancelar.setToolTipText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtFechaHora1.setEditable(false);
        txtFechaHora1.setBackground(new java.awt.Color(204, 255, 255));
        txtFechaHora1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtFechaHora1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCodUsuario1.setEditable(false);
        txtCodUsuario1.setBackground(new java.awt.Color(204, 255, 255));
        txtCodUsuario1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtCodUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodUsuario1ActionPerformed(evt);
            }
        });

        txtNomUsuario1.setEditable(false);
        txtNomUsuario1.setBackground(new java.awt.Color(204, 255, 255));
        txtNomUsuario1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtCodUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtNomUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre Sucursal:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setText("Cantidad:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));
        jPanel4.add(textNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 19, 210, -1));

        textFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCantidadActionPerformed(evt);
            }
        });
        jPanel4.add(textFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 70, -1));
        jPanel4.add(textFieldNombreSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 57, 210, -1));

        jLabel4.setText("Stock Minimo:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel5.setText("Tipo Articulo:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        textFieldStockMinimo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textFieldStockMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldStockMinimoActionPerformed(evt);
            }
        });
        jPanel4.add(textFieldStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 70, -1));

        textFieldTipoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTipoArticuloActionPerformed(evt);
            }
        });
        jPanel4.add(textFieldTipoArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 210, -1));

        jLabel1.setText("Nombre Articulo:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_botonGuardarActionPerformed

    
    public void guardar() {

        sessionHibernate();
        st.beginTransaction();

        Date fecha = new Date();
        FormatearNumero f = new FormatearNumero();
        StExistenciaSuc e = new StExistenciaSuc();
        e.setId(entidad.getId());
        e.setMtSucursales(entidad.getMtSucursales());
        e.setCantidad(new BigDecimal(textFieldCantidad.getText()));
        e.setMtArticulos(entidad.getMtArticulos());
        e.setStockMinimo(new BigDecimal (textFieldStockMinimo.getText()));
        e.setUsuarioMod(usuario);
        e.setFechaMod(fecha);
        st.saveOrUpdate(e);
        st.getTransaction().commit();
        st.close();
        JOptionPane.showMessageDialog(null, "Registro guardado");
        dispose();
    }

        
        
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        cancelar ();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void cancelar(){
                   int selec = JOptionPane.showConfirmDialog(null,
                       "¿Desea cancelar la edición?.", "Confirmacion", JOptionPane.YES_NO_OPTION);
                   System.out.println("el valor de select es " + String.valueOf(selec));
                   if (selec == 0){
                   this.dispose();
               }
                   
       }
    
    

    private void txtCodUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodUsuario1ActionPerformed

    private void textFieldStockMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldStockMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldStockMinimoActionPerformed

    private void textFieldTipoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTipoArticuloActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textFieldTipoArticuloActionPerformed

    private void textFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCantidadActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField textFieldCantidad;
    private javax.swing.JTextField textFieldNombreSucursal;
    private javax.swing.JTextField textFieldStockMinimo;
    private javax.swing.JTextField textFieldTipoArticulo;
    private javax.swing.JTextField textNombreArticulo;
    private javax.swing.JTextField txtCodUsuario1;
    private javax.swing.JTextField txtFechaHora1;
    private javax.swing.JTextField txtNomUsuario1;
    // End of variables declaration//GEN-END:variables

    

public void sessionHibernate() {
        st = HibernateUtil.getSessionFactory().openSession();
    }

}
