/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.seguridad;

import com.entidades.MtUsuarios;
import java.awt.HeadlessException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import util.HibernateUtil;

/**
 *
 * @author Carlos Patiño
 */
public class CambioContrasena extends javax.swing.JFrame {

    private String usuario;
    private String contrasena;

    /**
     * Creates new form frm_login_cambioContrasena
     */
    public CambioContrasena() {
        initComponents();
    }

    public CambioContrasena(String user, String pass) {
        initComponents();
        hibernateSession();
        this.setUsuario(user);
        this.setContrasena(pass);
        lblUsuario.setText(usuario);
    }

    private Session st;
    private DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_loginCambioContrasenaRep = new javax.swing.JPasswordField();
        txt_loginContrasenaActual = new javax.swing.JPasswordField();
        txt_loginContrasenaNueva = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmd_cambiar = new javax.swing.JButton();
        cmd_cancelar = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frm_login_cambioContrasena"); // NOI18N
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Repetir contraseña");

        txt_loginCambioContrasenaRep.setMaximumSize(new java.awt.Dimension(20, 20));

        txt_loginContrasenaActual.setMaximumSize(new java.awt.Dimension(20, 20));
        txt_loginContrasenaActual.setName(""); // NOI18N

        txt_loginContrasenaNueva.setMaximumSize(new java.awt.Dimension(20, 20));
        txt_loginContrasenaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginContrasenaNuevaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nueva contraseña");

        jLabel1.setText("Contraseña Actual");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_loginCambioContrasenaRep, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_loginContrasenaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_loginContrasenaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_loginContrasenaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_loginContrasenaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_loginCambioContrasenaRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cambiar contraseña de acceso");

        cmd_cambiar.setText("Aceptar");
        cmd_cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_cambiarActionPerformed(evt);
            }
        });

        cmd_cancelar.setText("Cancelar");
        cmd_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_cancelarActionPerformed(evt);
            }
        });

        lblUsuario.setText("...");
        lblUsuario.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(cmd_cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmd_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuario)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_cambiar)
                    .addComponent(cmd_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUsuario.getAccessibleContext().setAccessibleName("lblUsuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_cambiarActionPerformed
        validarCamposVacios();
        Date fecha = new Date();
        if (this.txt_loginContrasenaActual.getText().equals(this.getContrasena())) {
            if (this.txt_loginContrasenaNueva.getText().equals(this.txt_loginCambioContrasenaRep.getText())) {
                try {
                    MtUsuarios user = (MtUsuarios) st.load(MtUsuarios.class, this.getUsuario());
                    user.setContasenia(this.txt_loginContrasenaNueva.getText());
                    user.setUsuarioMod(usuario);
                    user.setFechaMod(fecha);
                    user.setAccionMod("Editar");
                    st.beginTransaction();
                    st.update(user);
                    st.getTransaction().commit();
                    JOptionPane.showMessageDialog(null, "Contraseña cambiada satisfactoriamente.",
                            "Cambio de Contraseña", JOptionPane.INFORMATION_MESSAGE);
                    arranque();
                    this.cmd_cancelar.setText("Cerrar");
                } catch (HibernateException | HeadlessException e) {
                    st.beginTransaction().rollback();
                    JOptionPane.showMessageDialog(null, "Se ha producido un error al intentar cambiar contraseña",
                            "Cambio de Contraseña", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "La nueva contrasena ingresada no coincide. Verificar datos",
                        "Cambio de Contraseña", JOptionPane.ERROR_MESSAGE);
                this.txt_loginContrasenaNueva.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "La contraseña actual no corresponde con la ingresada. Intente de nuevo.",
                    "Cambio de Contraseña", JOptionPane.ERROR_MESSAGE);
            this.txt_loginContrasenaActual.grabFocus();
        }
    }//GEN-LAST:event_cmd_cambiarActionPerformed

    private void cmd_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_cancelarActionPerformed
        this.txt_loginContrasenaNueva.setText("");
        this.txt_loginContrasenaActual.setText("");
        this.txt_loginCambioContrasenaRep.setText("");
        this.st.close();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cmd_cancelarActionPerformed

    private void txt_loginContrasenaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginContrasenaNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loginContrasenaNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CambioContrasena().setVisible(true);
            }
        });
    }

    private void setUsuario(String user) {
        this.usuario = user;
    }

    private void setContrasena(String pass) {
        this.contrasena = pass;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public String getContrasena() {
        return this.contrasena;
    }

    public void validarCamposVacios() {
        if (this.txt_loginCambioContrasenaRep.getText().isEmpty()
                || this.txt_loginContrasenaActual.getText().isEmpty()
                || this.txt_loginContrasenaNueva.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Existen campos vacíos. Verificar datos.",
                    "Cambio de Contraseña", JOptionPane.ERROR_MESSAGE);
            this.txt_loginContrasenaActual.grabFocus();
        }
    }

    public void arranque() {
        this.txt_loginCambioContrasenaRep.setText("");
        this.txt_loginContrasenaNueva.setText("");
        this.txt_loginContrasenaActual.setText("");
    }

    public void hibernateSession() {
        st = HibernateUtil.getSessionFactory().openSession();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_cambiar;
    private javax.swing.JButton cmd_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txt_loginCambioContrasenaRep;
    private javax.swing.JPasswordField txt_loginContrasenaActual;
    private javax.swing.JPasswordField txt_loginContrasenaNueva;
    // End of variables declaration//GEN-END:variables
}
